version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: 'frontend'
    ports:
      - '80:80'
    depends_on:
      - backend
  
  backend:
    build: ./backend
    container_name: 'backend'
    ports:
      - '8000:8000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./worker/files:/app/files
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'

  redis:
    image: redis:alpine
    container_name: 'redis'
    ports:
      - '6379:6379'